/*  This file is part of GeckoCIRCUITS. Copyright (C) ETH Zurich, Gecko-Simulations AG
 *
 *  GeckoCIRCUITS is free software: you can redistribute it and/or modify it under
 *  the terms of the GNU General Public License as published by the Free Software
 *  Foundation, either version 3 of the License, or (at your option) any later version.
 *
 *  GeckoCIRCUITS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 *  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *  PURPOSE.  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with
 *  GeckoCIRCUITS.  If not, see <http://www.gnu.org/licenses/>.
 */
package gecko.core.simulation.application;

import gecko.core.circuit.circuitcomponents.CircuitTypCore;
import gecko.core.circuit.netlist.CircuitNetlist;
import gecko.core.simulation.HeadlessSimulationEngine;
import gecko.core.simulation.SimulationConfig;
import gecko.core.simulation.SimulationResult;
import gecko.core.testutil.TraceComparisonHelper;
import gecko.core.testutil.TraceComparisonHelper.ComparisonResult;
import gecko.core.testutil.TraceComparisonHelper.StepData;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Application-level golden trace comparison for the buck_simple circuit.
 *
 * <p>Loads the golden trace generated by the proven SimulationsKern (via
 * TraceGeneratorTest) and compares it step-by-step against the headless
 * HeadlessSimulationEngine output. This test is tagged "application" and
 * excluded from default test runs.
 *
 * <p>Because SimulationsKern and HeadlessSimulationEngine may assign different
 * node indices when parsing the same .ipes file, the comparison automatically
 * discovers the node mapping at step 0 (by matching unique initial values) and
 * applies it to all subsequent steps.
 *
 * <p>Named signals (switch/diode R, gate) are compared directly by name.
 *
 * <p>When this test fails, it reports the FIRST divergent step and variable,
 * enabling precise root-cause identification:
 * <ul>
 *   <li>p[] diverges → matrix build or solve issue</li>
 *   <li>i[] diverges → current calculation or history shift issue</li>
 *   <li>R_sw diverges → gate signal application timing</li>
 *   <li>R_d diverges → diode iteration criteria</li>
 * </ul>
 */
@Tag("application")
public class BuckSimpleApplicationTest {

    private static final String GOLDEN_TRACE = "/traces/buck_simple_trace.csv.gz";
    private static final String CIRCUIT_FILE_RESOURCE = "/ipes/buck_simple.ipes";
    private static final double RELATIVE_TOLERANCE = 0.01; // 1%

    @Test
    void namedSignalComparison() throws Exception {
        List<StepData> goldenTrace = TraceComparisonHelper.loadTrace(GOLDEN_TRACE);
        assertFalse(goldenTrace.isEmpty(), "Golden trace is empty");

        String circuitPath = extractCircuitFile();
        List<StepData> actualTrace = runSimulationWithTraceCapture(circuitPath);

        System.out.println("Golden: " + goldenTrace.size() + " steps, Actual: " + actualTrace.size() + " steps");

        // Compare named signals (switch/diode R, gate) — these are index-independent
        int minLen = Math.min(goldenTrace.size(), actualTrace.size());
        List<String> failures = new ArrayList<>();

        for (int step = 0; step < minLen; step++) {
            StepData g = goldenTrace.get(step);
            StepData a = actualTrace.get(step);

            // Compare switch resistances by name
            for (Map.Entry<String, Double> entry : g.switchR().entrySet()) {
                Double actualVal = a.switchR().get(entry.getKey());
                if (actualVal != null && !withinTolerance(entry.getValue(), actualVal)) {
                    failures.add(String.format("Step %d (t=%.6e): R_sw_%s expected=%.6e actual=%.6e",
                            step, g.time(), entry.getKey(), entry.getValue(), actualVal));
                    break;
                }
            }

            // Compare diode resistances by name
            for (Map.Entry<String, Double> entry : g.diodeR().entrySet()) {
                Double actualVal = a.diodeR().get(entry.getKey());
                if (actualVal != null && !withinTolerance(entry.getValue(), actualVal)) {
                    failures.add(String.format("Step %d (t=%.6e): R_d_%s expected=%.6e actual=%.6e",
                            step, g.time(), entry.getKey(), entry.getValue(), actualVal));
                    break;
                }
            }

            // Compare gate signals by name
            for (Map.Entry<String, Double> entry : g.gateSignals().entrySet()) {
                Double actualVal = a.gateSignals().get(entry.getKey());
                if (actualVal != null && !withinTolerance(entry.getValue(), actualVal)) {
                    failures.add(String.format("Step %d (t=%.6e): gate_%s expected=%.6e actual=%.6e",
                            step, g.time(), entry.getKey(), entry.getValue(), actualVal));
                    break;
                }
            }

            if (!failures.isEmpty()) break; // Report only first divergence
        }

        if (!failures.isEmpty()) {
            fail("Named signal comparison failures:\n  " + String.join("\n  ", failures));
        }

        System.out.println("PASS: buck_simple named signals match (" + minLen + " steps)");
    }

    @Test
    void nodeVoltageComparisonWithAutoMapping() throws Exception {
        List<StepData> goldenTrace = TraceComparisonHelper.loadTrace(GOLDEN_TRACE);
        assertFalse(goldenTrace.isEmpty(), "Golden trace is empty");

        String circuitPath = extractCircuitFile();
        List<StepData> actualTrace = runSimulationWithTraceCapture(circuitPath);

        // Discover node mapping from step 0 (match by value)
        int[] nodeMapping = discoverNodeMapping(goldenTrace.get(0).nodeVoltages(),
                actualTrace.get(0).nodeVoltages());

        System.out.println("Node mapping (golden→actual): " + Arrays.toString(nodeMapping));

        // Compare node voltages using discovered mapping
        int minLen = Math.min(goldenTrace.size(), actualTrace.size());
        for (int step = 0; step < minLen; step++) {
            StepData g = goldenTrace.get(step);
            StepData a = actualTrace.get(step);

            for (int gi = 0; gi < nodeMapping.length; gi++) {
                int ai = nodeMapping[gi];
                if (ai < 0 || ai >= a.nodeVoltages().length) continue;

                double expected = g.nodeVoltages()[gi];
                double actual = a.nodeVoltages()[ai];

                if (!withinTolerance(expected, actual)) {
                    fail(String.format(
                            "Node voltage mismatch at step %d (t=%.6e): golden p[%d] → actual p[%d]\n"
                                    + "  Expected: %.12e\n  Actual:   %.12e\n  Rel diff: %.4f%%\n"
                                    + "  Golden all: %s\n  Actual all: %s",
                            step, g.time(), gi, ai, expected, actual,
                            Math.abs(expected - actual) / Math.max(Math.abs(expected), 1e-15) * 100,
                            Arrays.toString(g.nodeVoltages()),
                            Arrays.toString(a.nodeVoltages())));
                }
            }
        }

        System.out.println("PASS: buck_simple mapped node voltages match (" + minLen + " steps)");
    }

    @Test
    void goldenTraceStepCountMatches() throws Exception {
        List<StepData> goldenTrace = TraceComparisonHelper.loadTrace(GOLDEN_TRACE);
        String circuitPath = extractCircuitFile();
        List<StepData> actualTrace = runSimulationWithTraceCapture(circuitPath);

        // Allow small difference in step count (±1 due to boundary conditions)
        assertTrue(Math.abs(goldenTrace.size() - actualTrace.size()) <= 1,
                "Step count mismatch: golden=" + goldenTrace.size() + " actual=" + actualTrace.size());
    }

    /**
     * Discovers node mapping by matching values at step 0.
     * Returns array where result[goldenIdx] = actualIdx, or -1 if no match.
     */
    private static int[] discoverNodeMapping(double[] goldenValues, double[] actualValues) {
        int[] mapping = new int[goldenValues.length];
        boolean[] used = new boolean[actualValues.length];
        Arrays.fill(mapping, -1);

        // First pass: exact matches (ground node = 0)
        for (int gi = 0; gi < goldenValues.length; gi++) {
            for (int ai = 0; ai < actualValues.length; ai++) {
                if (!used[ai] && Math.abs(goldenValues[gi] - actualValues[ai]) < 1e-10) {
                    mapping[gi] = ai;
                    used[ai] = true;
                    break;
                }
            }
        }

        // Second pass: closest match for unmatched (within 10% tolerance)
        for (int gi = 0; gi < goldenValues.length; gi++) {
            if (mapping[gi] >= 0) continue;
            double bestDist = Double.MAX_VALUE;
            int bestAi = -1;
            for (int ai = 0; ai < actualValues.length; ai++) {
                if (used[ai]) continue;
                double dist = Math.abs(goldenValues[gi] - actualValues[ai]);
                if (dist < bestDist) {
                    bestDist = dist;
                    bestAi = ai;
                }
            }
            if (bestAi >= 0) {
                double relDiff = Math.abs(goldenValues[gi]) > 1e-15
                        ? bestDist / Math.abs(goldenValues[gi]) : bestDist;
                if (relDiff < 0.1) { // 10% tolerance for mapping discovery
                    mapping[gi] = bestAi;
                    used[bestAi] = true;
                }
            }
        }

        return mapping;
    }

    private List<StepData> runSimulationWithTraceCapture(String circuitPath) {
        HeadlessSimulationEngine engine = new HeadlessSimulationEngine();

        // Collect per-step trace data
        List<StepData> trace = new ArrayList<>();

        engine.setStepTraceListener((time, nodeVoltages, currents, netlist) -> {
            // Deep copy arrays since they're reused
            double[] pCopy = Arrays.copyOf(nodeVoltages, nodeVoltages.length);
            double[] iCopy = Arrays.copyOf(currents, currents.length);

            // Build index→name reverse map from netlist
            Map<Integer, String> indexToName = new HashMap<>();
            for (Map.Entry<String, Integer> e : netlist.getComponentNameToIndex().entrySet()) {
                indexToName.put(e.getValue(), e.getKey());
            }

            Map<String, Double> switchR = new LinkedHashMap<>();
            Map<String, Double> diodeR = new LinkedHashMap<>();
            Map<String, Double> gateSignals = new LinkedHashMap<>();

            for (int i = 0; i < netlist.getElementCount(); i++) {
                CircuitTypCore type = netlist.getType(i);
                double[] params = netlist.getParameter(i);
                String name = indexToName.getOrDefault(i, "elem" + i);

                if (type == CircuitTypCore.LK_S || type == CircuitTypCore.LK_MOSFET) {
                    switchR.put(name, params[0]);
                    gateSignals.put(name, params.length > 8 ? params[8] : 0.0);
                } else if (type == CircuitTypCore.LK_D || type == CircuitTypCore.LK_THYR
                        || type == CircuitTypCore.LK_IGBT) {
                    diodeR.put(name, params[0]);
                }
            }

            trace.add(new StepData(time, pCopy, iCopy, switchR, diodeR, gateSignals));
        });

        SimulationConfig config = SimulationConfig.builder()
                .circuitFile(circuitPath)
                .build();

        SimulationResult result = engine.runSimulation(config);
        assertTrue(result.isSuccess(), "Simulation failed: " + result.getErrorMessage());

        return trace;
    }

    private static boolean withinTolerance(double expected, double actual) {
        double absDiff = Math.abs(expected - actual);
        double absExpected = Math.abs(expected);
        if (absExpected < 1e-15) {
            return absDiff < RELATIVE_TOLERANCE;
        }
        return (absDiff / absExpected) <= RELATIVE_TOLERANCE;
    }

    private String extractCircuitFile() throws IOException {
        java.io.InputStream is = getClass().getResourceAsStream(CIRCUIT_FILE_RESOURCE);
        if (is == null) {
            fail("Circuit file resource not found: " + CIRCUIT_FILE_RESOURCE
                    + " (copy buck_simple.ipes to src/test/resources/ipes/)");
            return null;
        }
        java.nio.file.Path temp = java.nio.file.Files.createTempFile("buck_simple_", ".ipes");
        temp.toFile().deleteOnExit();
        java.nio.file.Files.copy(is, temp, java.nio.file.StandardCopyOption.REPLACE_EXISTING);
        is.close();
        return temp.toAbsolutePath().toString();
    }
}
